---
name: 🐛 Bug Report
about: Report a bug to help us improve SkillLearn
title: '[BUG] '
labels: ['bug']
assignees: ''

---

## 🐛 Bug Description
A clear and concise description of what the bug is.

## 🔍 Steps to Reproduce
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## ✅ Expected Behavior
A clear and concise description of what you expected to happen.

## ❌ Actual Behavior
A clear and concise description of what actually happened.

## 🖼️ Screenshots
If applicable, add screenshots to help explain your problem.

## 🌐 Environment
- **OS**: [e.g., Windows 11, macOS Big Sur, Ubuntu 20.04]
- **Browser**: [e.g., Chrome 96, Firefox 95, Safari 15]
- **PHP Version**: [e.g., 8.1.0]
- **Laravel Version**: [e.g., 10.x]

## 📱 Device Information
- **Device**: [e.g., Desktop, iPhone 12, Samsung Galaxy S21]
- **Screen Resolution**: [e.g., 1920x1080, 375x667]

## 📋 Additional Context
Add any other context about the problem here.

## 🔧 Possible Solution
If you have ideas on how to fix this issue, please describe them here.

---

### Checklist
- [ ] I have checked the [FAQ](docs/USER-GUIDE.md#-faq) and [documentation](docs/)
- [ ] I have searched for existing issues
- [ ] I have provided all the required information
- [ ] I can reproduce this issue consistently
